//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AwesomeBlog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class blogstuuf
    {
        public blogstuuf()
        {
            this.Comments = new HashSet<Comment>();
        }
    
        public int PostID { get; set; }
        public string Image { get; set; }
        public string Title { get; set; }
        public System.DateTime DatePosted { get; set; }
        public string PosterName { get; set; }
        public string Message { get; set; }
        public int Rating { get; set; }
        public int viewCount { get; set; }
        public string tags { get; set; }
    
        public virtual ICollection<Comment> Comments { get; set; }
    }
}
